version: "3.5"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    volumes:
      - ./app:/go/src/jongme/app
      - ./app:/uploads
    environment:
      - TZ=Asia/Bangkok
      - APP_ENV=development
      - PORT=8083
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGOUSERNAME}
      - MONGO_PASSWORD=${MONGOPASSWORD}
      - ISSUER=botioPlatform
      - JWT_SECRET=${JWTSECRET}
      - APP_ID=${FBAPIKEY}
      - APP_SECRET=${FBAPISECRET}
      - WEB_URL=${WEBURL}
      - VALIDATION_TOKEN=my_jongme_token
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - mongo
    networks:
      - backend
networks:
  backend:
    name: backend
volumes:
  mongodb-data:
